import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import docPaths from "@/lib/generated/doc-paths.json";
import pagePaths from "@/lib/generated/page-paths.json";

export const config = {
  matcher: ["/((?!_next|api|\\.well-known|r/|[\\w-]+\\.\\w+).*)"],
};

const MARKDOWN_MEDIA_TYPE = /(?:^|,\s*)text\/markdown(?:\s*;|\s*,|\s*$)/iu;
const TRAILING_SLASHES = /\/+$/u;

/*
 * The two catch-alls, `[...slug]` and `docs/[[...slug]]`, match every path in
 * the zone, and under Cache Components an unmatched param is answered with the
 * route's prerendered App Shell. That response is a 200 and it is already on the
 * wire before the slug is read, so the `notFound()` inside each Suspense
 * boundary can only swap the body: `/ui/ui` and `/ui/docs/anything` returned 200
 * and read to a crawler as real pages. `dynamicParams = false`, the documented
 * cure, is rejected outright by `next build` while `cacheComponents` is on. The
 * proxy is the only layer left that still owns the status code, so it answers
 * the question Next no longer can: is this a page at all?
 *
 * The content paths are generated by `content-collections.ts` on every build.
 * These are the routes that exist as files under `app/` instead, so nothing
 * generated knows about them. The matcher above already drops anything with a
 * file extension, which covers `/sitemap.xml`, `/robots.txt` and the icons; add
 * to this list when adding a static route without one.
 */
const APP_ROUTES = ["/", "/docs/components", "/og", "/opengraph-image", "/theme-visualizer"];

const KNOWN_PATHS = new Set([...APP_ROUTES, ...docPaths, ...pagePaths]);

function prefersMarkdown(accept: string | null): boolean {
  if (!accept) {
    return false;
  }
  return MARKDOWN_MEDIA_TYPE.test(accept);
}

export default function proxy(request: NextRequest) {
  const accept = request.headers.get("accept");
  const pathname = request.nextUrl.pathname.replace(TRAILING_SLASHES, "") || "/";

  if (prefersMarkdown(accept)) {
    const url = request.nextUrl.clone();
    url.pathname = `/api/markdown${pathname === "/" ? "" : pathname}`;
    const rewritten = NextResponse.rewrite(url);
    rewritten.headers.set("Vary", "Accept");
    return rewritten;
  }

  if (!KNOWN_PATHS.has(pathname)) {
    const url = request.nextUrl.clone();
    url.pathname = "/_not-found";
    const rewritten = NextResponse.rewrite(url);
    rewritten.headers.set("Vary", "Accept");
    return rewritten;
  }

  const response = NextResponse.next();
  response.headers.set("Vary", "Accept");
  return response;
}
