// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/aspect-ratio.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/aspect-ratio.tsx")),
      source: "",
      meta: undefined,
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/avatar.tsx")),
      source: "",
      meta: undefined,
    },
    "bar-list": {
      name: "bar-list",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/bar-list.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/bar-list.tsx")),
      source: "",
      meta: undefined,
    },
    "bottom-sheet": {
      name: "bottom-sheet",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/bottom-sheet.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/bottom-sheet.tsx")),
      source: "",
      meta: undefined,
    },
    "breadcrumb": {
      name: "breadcrumb",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/breadcrumb.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/breadcrumb.tsx")),
      source: "",
      meta: undefined,
    },
    "glass-label": {
      name: "glass-label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/glass-label.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/glass-label.tsx")),
      source: "",
      meta: undefined,
    },
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      meta: undefined,
    },
    "alert": {
      name: "alert",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/alert.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert.tsx")),
      source: "",
      meta: undefined,
    },
    "form-control": {
      name: "form-control",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/form-control.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/form-control.tsx")),
      source: "",
      meta: undefined,
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      meta: undefined,
    },
    "circular-progress": {
      name: "circular-progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/circular-progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/circular-progress.tsx")),
      source: "",
      meta: undefined,
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/badge.tsx")),
      source: "",
      meta: undefined,
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: ["spinner"],
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      meta: undefined,
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      meta: undefined,
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/collapsible.tsx")),
      source: "",
      meta: undefined,
    },
    "command": {
      name: "command",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/ui/command.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/command.tsx")),
      source: "",
      meta: undefined,
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "calendar": {
      name: "calendar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/calendar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/calendar.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel": {
      name: "carousel",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/carousel.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/carousel.tsx")),
      source: "",
      meta: undefined,
    },
    "color-picker": {
      name: "color-picker",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","label","popover"],
      files: [{
        path: "registry/default/ui/color-picker.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/color-picker.tsx")),
      source: "",
      meta: undefined,
    },
    "combobox": {
      name: "combobox",
      description: "",
      type: "registry:ui",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/ui/combobox.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/combobox.tsx")),
      source: "",
      meta: undefined,
    },
    "copy": {
      name: "copy",
      description: "",
      type: "registry:ui",
      registryDependencies: ["tooltip"],
      files: [{
        path: "registry/default/ui/copy.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/copy.tsx")),
      source: "",
      meta: undefined,
    },
    "currency-input": {
      name: "currency-input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/currency-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/currency-input.tsx")),
      source: "",
      meta: undefined,
    },
    "data-table": {
      name: "data-table",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/data-table.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/data-table.tsx")),
      source: "",
      meta: undefined,
    },
    "date-picker": {
      name: "date-picker",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","calendar","popover"],
      files: [{
        path: "registry/default/ui/date-picker.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/date-picker.tsx")),
      source: "",
      meta: undefined,
    },
    "date-range-dropdown": {
      name: "date-range-dropdown",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","calendar","popover","select"],
      files: [{
        path: "registry/default/ui/date-range-dropdown.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/date-range-dropdown.tsx")),
      source: "",
      meta: undefined,
    },
    "date-range-picker": {
      name: "date-range-picker",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","calendar","popover"],
      files: [{
        path: "registry/default/ui/date-range-picker.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/date-range-picker.tsx")),
      source: "",
      meta: undefined,
    },
    "heading": {
      name: "heading",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/heading.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/heading.tsx")),
      source: "",
      meta: undefined,
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      meta: undefined,
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/kbd.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/kbd.tsx")),
      source: "",
      meta: undefined,
    },
    "input-otp": {
      name: "input-otp",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input-otp.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/input-otp.tsx")),
      source: "",
      meta: undefined,
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/label.tsx")),
      source: "",
      meta: undefined,
    },
    "list": {
      name: "list",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/list.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/list.tsx")),
      source: "",
      meta: undefined,
    },
    "menubar": {
      name: "menubar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/menubar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/menubar.tsx")),
      source: "",
      meta: undefined,
    },
    "multi-combobox": {
      name: "multi-combobox",
      description: "",
      type: "registry:ui",
      registryDependencies: ["badge"],
      files: [{
        path: "registry/default/ui/multi-combobox.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/multi-combobox.tsx")),
      source: "",
      meta: undefined,
    },
    "multi-select": {
      name: "multi-select",
      description: "",
      type: "registry:ui",
      registryDependencies: ["badge","button","checkbox","command","label"],
      files: [{
        path: "registry/default/ui/multi-select.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/multi-select.tsx")),
      source: "",
      meta: undefined,
    },
    "phone-input": {
      name: "phone-input",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","command","input","popover","scroll-area"],
      files: [{
        path: "registry/default/ui/phone-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/phone-input.tsx")),
      source: "",
      meta: undefined,
    },
    "popover": {
      name: "popover",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/popover.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/popover.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/scroll-area.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-menu": {
      name: "scroll-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/scroll-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      meta: undefined,
    },
    "separator": {
      name: "separator",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/separator.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/separator.tsx")),
      source: "",
      meta: undefined,
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/progress.tsx")),
      source: "",
      meta: undefined,
    },
    "progress-list": {
      name: "progress-list",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/progress-list.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/progress-list.tsx")),
      source: "",
      meta: undefined,
    },
    "prompt": {
      name: "prompt",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","heading"],
      files: [{
        path: "registry/default/ui/prompt.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/prompt.tsx")),
      source: "",
      meta: undefined,
    },
    "radio-group": {
      name: "radio-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/radio-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/radio-group.tsx")),
      source: "",
      meta: undefined,
    },
    "render-prompt": {
      name: "render-prompt",
      description: "",
      type: "registry:ui",
      registryDependencies: ["prompt","input","label"],
      files: [{
        path: "registry/default/ui/render-prompt.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/render-prompt.tsx")),
      source: "",
      meta: undefined,
    },
    "responsive-sheet": {
      name: "responsive-sheet",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog","sheet"],
      files: [{
        path: "registry/default/ui/responsive-sheet.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/responsive-sheet.tsx")),
      source: "",
      meta: undefined,
    },
    "responsive-sheet-content": {
      name: "responsive-sheet-content",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog","sheet"],
      files: [{
        path: "registry/default/ui/responsive-sheet-content.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/responsive-sheet-content.tsx")),
      source: "",
      meta: undefined,
    },
    "search": {
      name: "search",
      description: "",
      type: "registry:ui",
      registryDependencies: ["form-control","input"],
      files: [{
        path: "registry/default/ui/search.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/search.tsx")),
      source: "",
      meta: undefined,
    },
    "share": {
      name: "share",
      description: "",
      type: "registry:ui",
      registryDependencies: ["tooltip"],
      files: [{
        path: "registry/default/ui/share.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/share.tsx")),
      source: "",
      meta: undefined,
    },
    "sheet": {
      name: "sheet",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sheet.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sheet.tsx")),
      source: "",
      meta: undefined,
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner": {
      name: "sonner",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sonner.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sonner.tsx")),
      source: "",
      meta: undefined,
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      meta: undefined,
    },
    "table": {
      name: "table",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/table.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/table.tsx")),
      source: "",
      meta: undefined,
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      meta: undefined,
    },
    "slider": {
      name: "slider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/slider.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/slider.tsx")),
      source: "",
      meta: undefined,
    },
    "spinner": {
      name: "spinner",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/spinner.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/spinner.tsx")),
      source: "",
      meta: undefined,
    },
    "stat": {
      name: "stat",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/stat.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/stat.tsx")),
      source: "",
      meta: undefined,
    },
    "stepper": {
      name: "stepper",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/stepper.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/stepper.tsx")),
      source: "",
      meta: undefined,
    },
    "sticker": {
      name: "sticker",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sticker.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sticker.tsx")),
      source: "",
      meta: undefined,
    },
    "text": {
      name: "text",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/text.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/text.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/textarea.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle-group.tsx")),
      source: "",
      meta: undefined,
    },
    "toolbar": {
      name: "toolbar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","tooltip"],
      files: [{
        path: "registry/default/ui/toolbar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toolbar.tsx")),
      source: "",
      meta: undefined,
    },
    "tooltip": {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tooltip.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/tooltip.tsx")),
      source: "",
      meta: undefined,
    },
    "validation": {
      name: "validation",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/validation.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/validation.tsx")),
      source: "",
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      meta: undefined,
    },
    "spinner-demo": {
      name: "spinner-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["spinner"],
      files: [{
        path: "registry/default/examples/spinner-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/spinner-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "spinner-size": {
      name: "spinner-size",
      description: "",
      type: "registry:example",
      registryDependencies: ["spinner"],
      files: [{
        path: "registry/default/examples/spinner-size.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/spinner-size.tsx")),
      source: "",
      meta: undefined,
    },
    "spinner-stroke-width": {
      name: "spinner-stroke-width",
      description: "",
      type: "registry:example",
      registryDependencies: ["spinner"],
      files: [{
        path: "registry/default/examples/spinner-stroke-width.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/spinner-stroke-width.tsx")),
      source: "",
      meta: undefined,
    },
    "glass-label-demo": {
      name: "glass-label-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["glass-label"],
      files: [{
        path: "registry/default/examples/glass-label-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/glass-label-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "copy-demo": {
      name: "copy-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["copy","tabs","card","label","input","button"],
      files: [{
        path: "registry/default/examples/copy-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/copy-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "currency-input-demo": {
      name: "currency-input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["currency-input","label"],
      files: [{
        path: "registry/default/examples/currency-input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/currency-input-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "date-range-dropdown-demo": {
      name: "date-range-dropdown-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["date-range-dropdown","button","calendar","popover","select"],
      files: [{
        path: "registry/default/examples/date-range-dropdown-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/date-range-dropdown-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "multi-select-demo": {
      name: "multi-select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["multi-select","badge","command","button","checkbox","label"],
      files: [{
        path: "registry/default/examples/multi-select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/multi-select-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "progress-list-demo": {
      name: "progress-list-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["progress-list"],
      files: [{
        path: "registry/default/examples/progress-list-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/progress-list-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "form-control-demo": {
      name: "form-control-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["form-control","input"],
      files: [{
        path: "registry/default/examples/form-control-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/form-control-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-menu-demo": {
      name: "scroll-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-menu","button"],
      files: [{
        path: "registry/default/examples/scroll-menu-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/scroll-menu-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "search-demo": {
      name: "search-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["search","input","form-control"],
      files: [{
        path: "registry/default/examples/search-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/search-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "share-demo": {
      name: "share-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["share","button"],
      files: [{
        path: "registry/default/examples/share-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/share-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "stat-demo": {
      name: "stat-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["stat"],
      files: [{
        path: "registry/default/examples/stat-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stat-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "toolbar-demo": {
      name: "toolbar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toolbar","button","tooltip"],
      files: [{
        path: "registry/default/examples/toolbar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toolbar-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "sticker-demo": {
      name: "sticker-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sticker"],
      files: [{
        path: "registry/default/examples/sticker-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sticker-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "validation-demo": {
      name: "validation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["validation","button","input","label"],
      files: [{
        path: "registry/default/examples/validation-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/validation-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "color-picker-demo": {
      name: "color-picker-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["color-picker","label"],
      files: [{
        path: "registry/default/examples/color-picker-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/color-picker-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "bottom-sheet-demo": {
      name: "bottom-sheet-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["bottom-sheet","button"],
      files: [{
        path: "registry/default/examples/bottom-sheet-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/bottom-sheet-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "bar-list-demo": {
      name: "bar-list-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["bar-list"],
      files: [{
        path: "registry/default/examples/bar-list-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/bar-list-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "accordion-demo": {
      name: "accordion-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [{
        path: "registry/default/examples/accordion-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/accordion-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "alert-demo": {
      name: "alert-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert"],
      files: [{
        path: "registry/default/examples/alert-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/alert-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "alert-destructive": {
      name: "alert-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert"],
      files: [{
        path: "registry/default/examples/alert-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/alert-destructive.tsx")),
      source: "",
      meta: undefined,
    },
    "alert-dialog-demo": {
      name: "alert-dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert-dialog","button"],
      files: [{
        path: "registry/default/examples/alert-dialog-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/alert-dialog-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "aspect-ratio-demo": {
      name: "aspect-ratio-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["aspect-ratio"],
      files: [{
        path: "registry/default/examples/aspect-ratio-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/aspect-ratio-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "avatar-demo": {
      name: "avatar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: [{
        path: "registry/default/examples/avatar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/avatar-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "badge-demo": {
      name: "badge-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: [{
        path: "registry/default/examples/badge-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/badge-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "badge-destructive": {
      name: "badge-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: [{
        path: "registry/default/examples/badge-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/badge-destructive.tsx")),
      source: "",
      meta: undefined,
    },
    "badge-outline": {
      name: "badge-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: [{
        path: "registry/default/examples/badge-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/badge-outline.tsx")),
      source: "",
      meta: undefined,
    },
    "badge-green": {
      name: "badge-green",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: [{
        path: "registry/default/examples/badge-green.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/badge-green.tsx")),
      source: "",
      meta: undefined,
    },
    "breadcrumb-demo": {
      name: "breadcrumb-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["breadcrumb"],
      files: [{
        path: "registry/default/examples/breadcrumb-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/breadcrumb-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "breadcrumb-separator": {
      name: "breadcrumb-separator",
      description: "",
      type: "registry:example",
      registryDependencies: ["breadcrumb"],
      files: [{
        path: "registry/default/examples/breadcrumb-separator.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/breadcrumb-separator.tsx")),
      source: "",
      meta: undefined,
    },
    "breadcrumb-dropdown": {
      name: "breadcrumb-dropdown",
      description: "",
      type: "registry:example",
      registryDependencies: ["breadcrumb"],
      files: [{
        path: "registry/default/examples/breadcrumb-dropdown.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/breadcrumb-dropdown.tsx")),
      source: "",
      meta: undefined,
    },
    "breadcrumb-ellipsis": {
      name: "breadcrumb-ellipsis",
      description: "",
      type: "registry:example",
      registryDependencies: ["breadcrumb"],
      files: [{
        path: "registry/default/examples/breadcrumb-ellipsis.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/breadcrumb-ellipsis.tsx")),
      source: "",
      meta: undefined,
    },
    "breadcrumb-link": {
      name: "breadcrumb-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["breadcrumb"],
      files: [{
        path: "registry/default/examples/breadcrumb-link.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/breadcrumb-link.tsx")),
      source: "",
      meta: undefined,
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "button-secondary": {
      name: "button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-secondary.tsx")),
      source: "",
      meta: undefined,
    },
    "button-muted": {
      name: "button-muted",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-muted.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-muted.tsx")),
      source: "",
      meta: undefined,
    },
    "button-destructive": {
      name: "button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-destructive.tsx")),
      source: "",
      meta: undefined,
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-ghost.tsx")),
      source: "",
      meta: undefined,
    },
    "button-link": {
      name: "button-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-link.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-link.tsx")),
      source: "",
      meta: undefined,
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-loading.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-loading.tsx")),
      source: "",
      meta: undefined,
    },
    "button-as-child": {
      name: "button-as-child",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-as-child.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/button-as-child.tsx")),
      source: "",
      meta: undefined,
    },
    "calendar-demo": {
      name: "calendar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calendar"],
      files: [{
        path: "registry/default/examples/calendar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/calendar-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "card-demo": {
      name: "card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["card","button","switch"],
      files: [{
        path: "registry/default/examples/card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/card-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel-demo": {
      name: "carousel-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel"],
      files: [{
        path: "registry/default/examples/carousel-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/carousel-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel-size": {
      name: "carousel-size",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel"],
      files: [{
        path: "registry/default/examples/carousel-size.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/carousel-size.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel-spacing": {
      name: "carousel-spacing",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel"],
      files: [{
        path: "registry/default/examples/carousel-spacing.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/carousel-spacing.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel-orientation": {
      name: "carousel-orientation",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel"],
      files: [{
        path: "registry/default/examples/carousel-orientation.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/carousel-orientation.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel-api": {
      name: "carousel-api",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel"],
      files: [{
        path: "registry/default/examples/carousel-api.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/carousel-api.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel-plugin": {
      name: "carousel-plugin",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel"],
      files: [{
        path: "registry/default/examples/carousel-plugin.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/carousel-plugin.tsx")),
      source: "",
      meta: undefined,
    },
    "checkbox-demo": {
      name: "checkbox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [{
        path: "registry/default/examples/checkbox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/checkbox-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "checkbox-disabled": {
      name: "checkbox-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [{
        path: "registry/default/examples/checkbox-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/checkbox-disabled.tsx")),
      source: "",
      meta: undefined,
    },
    "checkbox-with-text": {
      name: "checkbox-with-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [{
        path: "registry/default/examples/checkbox-with-text.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/checkbox-with-text.tsx")),
      source: "",
      meta: undefined,
    },
    "collapsible-demo": {
      name: "collapsible-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["collapsible"],
      files: [{
        path: "registry/default/examples/collapsible-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/collapsible-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "combobox-demo": {
      name: "combobox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["command"],
      files: [{
        path: "registry/default/examples/combobox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/combobox-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "multi-combobox-demo": {
      name: "multi-combobox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["command","popover","badge"],
      files: [{
        path: "registry/default/examples/multi-combobox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/multi-combobox-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "command-demo": {
      name: "command-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["command"],
      files: [{
        path: "registry/default/examples/command-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/command-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "command-dialog": {
      name: "command-dialog",
      description: "",
      type: "registry:example",
      registryDependencies: ["command","dialog"],
      files: [{
        path: "registry/default/examples/command-dialog.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/command-dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "data-table-demo": {
      name: "data-table-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["data-table"],
      files: [{
        path: "registry/default/examples/data-table-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/data-table-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "date-picker-demo": {
      name: "date-picker-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","calendar","popover"],
      files: [{
        path: "registry/default/examples/date-picker-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/date-picker-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "date-picker-with-presets": {
      name: "date-picker-with-presets",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","calendar","popover","select"],
      files: [{
        path: "registry/default/examples/date-picker-with-presets.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/date-picker-with-presets.tsx")),
      source: "",
      meta: undefined,
    },
    "date-picker-with-range": {
      name: "date-picker-with-range",
      description: "",
      type: "registry:example",
      registryDependencies: ["button","calendar","popover"],
      files: [{
        path: "registry/default/examples/date-picker-with-range.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/date-picker-with-range.tsx")),
      source: "",
      meta: undefined,
    },
    "dialog-demo": {
      name: "dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/dialog-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "dialog-close-button": {
      name: "dialog-close-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog","button"],
      files: [{
        path: "registry/default/examples/dialog-close-button.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/dialog-close-button.tsx")),
      source: "",
      meta: undefined,
    },
    "dropdown-menu-demo": {
      name: "dropdown-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "registry/default/examples/dropdown-menu-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "dropdown-menu-checkboxes": {
      name: "dropdown-menu-checkboxes",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu","checkbox"],
      files: [{
        path: "registry/default/examples/dropdown-menu-checkboxes.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-checkboxes.tsx")),
      source: "",
      meta: undefined,
    },
    "radio-group-demo": {
      name: "radio-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["radio-group","label"],
      files: [{
        path: "registry/default/examples/radio-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/radio-group-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "dropdown-menu-radio-group": {
      name: "dropdown-menu-radio-group",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu","radio-group"],
      files: [{
        path: "registry/default/examples/dropdown-menu-radio-group.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-radio-group.tsx")),
      source: "",
      meta: undefined,
    },
    "input-demo": {
      name: "input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "input-disabled": {
      name: "input-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-disabled.tsx")),
      source: "",
      meta: undefined,
    },
    "input-file": {
      name: "input-file",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-file.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-file.tsx")),
      source: "",
      meta: undefined,
    },
    "input-with-button": {
      name: "input-with-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["input","button"],
      files: [{
        path: "registry/default/examples/input-with-button.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-with-button.tsx")),
      source: "",
      meta: undefined,
    },
    "input-with-label": {
      name: "input-with-label",
      description: "",
      type: "registry:example",
      registryDependencies: ["input","button","label"],
      files: [{
        path: "registry/default/examples/input-with-label.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-with-label.tsx")),
      source: "",
      meta: undefined,
    },
    "input-with-text": {
      name: "input-with-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["input","button","label"],
      files: [{
        path: "registry/default/examples/input-with-text.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-with-text.tsx")),
      source: "",
      meta: undefined,
    },
    "input-otp-demo": {
      name: "input-otp-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-otp"],
      files: [{
        path: "registry/default/examples/input-otp-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-otp-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "input-otp-pattern": {
      name: "input-otp-pattern",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-otp"],
      files: [{
        path: "registry/default/examples/input-otp-pattern.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-otp-pattern.tsx")),
      source: "",
      meta: undefined,
    },
    "input-otp-separator": {
      name: "input-otp-separator",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-otp"],
      files: [{
        path: "registry/default/examples/input-otp-separator.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-otp-separator.tsx")),
      source: "",
      meta: undefined,
    },
    "input-otp-controlled": {
      name: "input-otp-controlled",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-otp"],
      files: [{
        path: "registry/default/examples/input-otp-controlled.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/input-otp-controlled.tsx")),
      source: "",
      meta: undefined,
    },
    "phone-input-demo": {
      name: "phone-input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-input"],
      files: [{
        path: "registry/default/examples/phone-input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/phone-input-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "phone-input-disabled": {
      name: "phone-input-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-input"],
      files: [{
        path: "registry/default/examples/phone-input-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/phone-input-disabled.tsx")),
      source: "",
      meta: undefined,
    },
    "phone-input-clearable": {
      name: "phone-input-clearable",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-input"],
      files: [{
        path: "registry/default/examples/phone-input-clearable.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/phone-input-clearable.tsx")),
      source: "",
      meta: undefined,
    },
    "kbd-demo": {
      name: "kbd-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["kbd"],
      files: [{
        path: "registry/default/examples/kbd-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/kbd-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "label-demo": {
      name: "label-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["label"],
      files: [{
        path: "registry/default/examples/label-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/label-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "menubar-demo": {
      name: "menubar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["menubar"],
      files: [{
        path: "registry/default/examples/menubar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/menubar-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "popover-demo": {
      name: "popover-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["popover"],
      files: [{
        path: "registry/default/examples/popover-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/popover-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "circular-progress-demo": {
      name: "circular-progress-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["circular-progress","button","slider"],
      files: [{
        path: "registry/default/examples/circular-progress-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/circular-progress-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "progress-demo": {
      name: "progress-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["progress"],
      files: [{
        path: "registry/default/examples/progress-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/progress-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-area-demo": {
      name: "scroll-area-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-area"],
      files: [{
        path: "registry/default/examples/scroll-area-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/scroll-area-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-area-horizontal-demo": {
      name: "scroll-area-horizontal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-area"],
      files: [{
        path: "registry/default/examples/scroll-area-horizontal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/scroll-area-horizontal-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "select-demo": {
      name: "select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [{
        path: "registry/default/examples/select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/select-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "select-scrollable": {
      name: "select-scrollable",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [{
        path: "registry/default/examples/select-scrollable.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/select-scrollable.tsx")),
      source: "",
      meta: undefined,
    },
    "separator-demo": {
      name: "separator-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["separator"],
      files: [{
        path: "registry/default/examples/separator-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/separator-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "sheet-demo": {
      name: "sheet-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sheet"],
      files: [{
        path: "registry/default/examples/sheet-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sheet-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "sheet-side": {
      name: "sheet-side",
      description: "",
      type: "registry:example",
      registryDependencies: ["sheet"],
      files: [{
        path: "registry/default/examples/sheet-side.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sheet-side.tsx")),
      source: "",
      meta: undefined,
    },
    "responsive-sheet-demo": {
      name: "responsive-sheet-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["responsive-sheet","button","input","label"],
      files: [{
        path: "registry/default/examples/responsive-sheet-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/responsive-sheet-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "skeleton-demo": {
      name: "skeleton-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: [{
        path: "registry/default/examples/skeleton-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/skeleton-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "skeleton-card": {
      name: "skeleton-card",
      description: "",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: [{
        path: "registry/default/examples/skeleton-card.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/skeleton-card.tsx")),
      source: "",
      meta: undefined,
    },
    "slider-demo": {
      name: "slider-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["slider"],
      files: [{
        path: "registry/default/examples/slider-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/slider-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "sonner-demo": {
      name: "sonner-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner"],
      files: [{
        path: "registry/default/examples/sonner-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/sonner-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "switch-demo": {
      name: "switch-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["switch"],
      files: [{
        path: "registry/default/examples/switch-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/switch-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "table-demo": {
      name: "table-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["table"],
      files: [{
        path: "registry/default/examples/table-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/table-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "tabs-demo": {
      name: "tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: [{
        path: "registry/default/examples/tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/tabs-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea-demo": {
      name: "textarea-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea"],
      files: [{
        path: "registry/default/examples/textarea-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/textarea-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea-disabled": {
      name: "textarea-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea"],
      files: [{
        path: "registry/default/examples/textarea-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/textarea-disabled.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea-with-button": {
      name: "textarea-with-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea","button"],
      files: [{
        path: "registry/default/examples/textarea-with-button.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/textarea-with-button.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea-with-label": {
      name: "textarea-with-label",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea","label"],
      files: [{
        path: "registry/default/examples/textarea-with-label.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/textarea-with-label.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea-with-text": {
      name: "textarea-with-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea","label"],
      files: [{
        path: "registry/default/examples/textarea-with-text.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/textarea-with-text.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group-demo": {
      name: "toggle-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [{
        path: "registry/default/examples/toggle-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group-disabled": {
      name: "toggle-group-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [{
        path: "registry/default/examples/toggle-group-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-disabled.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group-lg": {
      name: "toggle-group-lg",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [{
        path: "registry/default/examples/toggle-group-lg.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-lg.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group-outline": {
      name: "toggle-group-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [{
        path: "registry/default/examples/toggle-group-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-outline.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group-sm": {
      name: "toggle-group-sm",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [{
        path: "registry/default/examples/toggle-group-sm.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-sm.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group-single": {
      name: "toggle-group-single",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [{
        path: "registry/default/examples/toggle-group-single.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-single.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-demo": {
      name: "toggle-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-disabled": {
      name: "toggle-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-disabled.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-lg": {
      name: "toggle-lg",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-lg.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-lg.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-secondary": {
      name: "toggle-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-secondary.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-sm": {
      name: "toggle-sm",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-sm.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-sm.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-with-text": {
      name: "toggle-with-text",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-with-text.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/toggle-with-text.tsx")),
      source: "",
      meta: undefined,
    },
    "tooltip-demo": {
      name: "tooltip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: [{
        path: "registry/default/examples/tooltip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/tooltip-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "stepper-demo": {
      name: "stepper-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["stepper","button"],
      files: [{
        path: "registry/default/examples/stepper-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stepper-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "stepper-vertical": {
      name: "stepper-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: ["stepper","button"],
      files: [{
        path: "registry/default/examples/stepper-vertical.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/stepper-vertical.tsx")),
      source: "",
      meta: undefined,
    },
    "list-demo": {
      name: "list-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["list"],
      files: [{
        path: "registry/default/examples/list-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/list-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "render-prompt-demo": {
      name: "render-prompt-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["render-prompt","button","prompt"],
      files: [{
        path: "registry/default/examples/render-prompt-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/render-prompt-demo.tsx")),
      source: "",
      meta: undefined,
    },
    "prompt-demo": {
      name: "prompt-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt","button"],
      files: [{
        path: "registry/default/examples/prompt-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/examples/prompt-demo.tsx")),
      source: "",
      meta: undefined,
    },
  },
}
